name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout app repo
      uses: actions/checkout@v5

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t myusername/myapp:${{ github.sha }} .

    - name: Push Docker image
      run: docker push myusername/myapp:${{ github.sha }}

    - name: Set output image tag
      id: image
      run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT
      
    # Optional: Trigger Helm repo workflow using repository_dispatch or update Helm chart here
